--CÁC CÂU LỆNH TẠO USER VÀ GÁN QUYỀN
 
CREATE USER ThuongMaiDienTu_Web IDENTIFIED BY TMDT_123456789;
ALTER USER ThuongMaiDienTu_Web QUOTA unlimited ON SYSTEM;
GRANT CREATE SESSION, CONNECT, RESOURCE, DBA TO ThuongMaiDienTu_Web;
GRANT ALL PRIVILEGES TO ThuongMaiDienTu_Web;

--------------------------------------------------------------------------------------------------------------------------------
-- NHÓM CÁC BẢNG QUẢN TRỊ VÀ NGƯỜI DÙNG

CREATE TABLE ThuongMaiDienTu_Web.Admins
(
	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
	username VARCHAR2(100) NOT NULL,
	fullname NVARCHAR2(200),
	gender VARCHAR2(15) DEFAULT 'male',
	"description" LONG,
	email VARCHAR2(100) NOT NULL,
	birthday DATE,
	avatar VARCHAR2(200),
	phone VARCHAR2(25),
	"password" VARCHAR2(200) NOT NULL,
	roleId INT NOT NULL,
	createAt TIMESTAMP,
	updateAt TIMESTAMP,
	
	CONSTRAINT PK_Admins PRIMARY KEY ("ID")
);

CREATE TABLE  ThuongMaiDienTu_Web."Roles"
(
	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
	"name" NVARCHAR2(100) NOT NULL,
	"description" LONG,
	createAt TIMESTAMP,
	updateAt TIMESTAMP,
	
	CONSTRAINT PK_Roles PRIMARY KEY ("ID")
 );
 
CREATE TABLE ThuongMaiDienTu_Web.Customers
(
    "ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
	username VARCHAR2(100) NOT NULL,
	fullname NVARCHAR2(200) DEFAULT 'Chua dat ten',
	gender VARCHAR2(15) DEFAULT 'male',
	"description" LONG,
	email VARCHAR2(100) NOT NULL,
	birthday DATE,
	avatar VARCHAR2(200),
	phone VARCHAR2(25),
	"password" VARCHAR2(200) NOT NULL,
	isActivated VARCHAR(10),
	createAt TIMESTAMP,
	updateAt TIMESTAMP,
    
    CONSTRAINT PK_Customers PRIMARY KEY ("ID")
);
 
--------------------------------------------------------------------------------------------------------------------------------
-- NHÓM CÁC BẢNG THÔNG TIN SẢN PHẨM

CREATE TABLE ThuongMaiDienTu_Web.Products
(
	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
	"name" VARCHAR2(200),
	"description" LONG,
	price DECIMAL(19,4) NOT NULL,
	discount DECIMAL(19,4),
	quanty INT NOT NULL,
	productCategoryId NUMBER NOT NULL,
    productStateId NUMBER NOT NULL,
	supplierId NUMBER NOT NULL,
	createAt TIMESTAMP,
	updateAt TIMESTAMP,
	
	CONSTRAINT PK_Products PRIMARY KEY ("ID")
);
 
CREATE TABLE ThuongMaiDienTu_Web.ProductStates
(
    "ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
	"name" NVARCHAR2(100) NOT NULL,
	"description" LONG,
	createAt TIMESTAMP,
	updateAt TIMESTAMP,
	
	CONSTRAINT PK_ProductStates PRIMARY KEY ("ID")
);
 
CREATE TABLE ThuongMaiDienTu_Web.ProductCategories
(
	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
	"name" NVARCHAR2(100) NOT NULL,
	"description" LONG,
	createAt TIMESTAMP,
	updateAt TIMESTAMP,
	
	CONSTRAINT PK_ProductCategories PRIMARY KEY ("ID")
);

CREATE TABLE ThuongMaiDienTu_Web.Suppliers
(
	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
	"name" NVARCHAR2(100) NOT NULL,
	"description" LONG,
	phone VARCHAR2(25),
	email VARCHAR2(100) NOT NULL,
	fax VARCHAR2(100),
	createAt TIMESTAMP,
	updateAt TIMESTAMP,
	
	CONSTRAINT PK_Suppliers PRIMARY KEY ("ID")
);
 
CREATE TABLE ThuongMaiDienTu_Web.ProductReviews
(
	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
	productId NUMBER NOT NULL,
	customerId NUMBER NOT NULL,
	rating FLOAT,
	"comment" LONG,
	parentId NUMBER,
	createAt TIMESTAMP,
	updateAt TIMESTAMP,
	
	CONSTRAINT PK_ProductReviews PRIMARY KEY ("ID")
);
 
CREATE TABLE ThuongMaiDienTu_Web.ProductImages
(
	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
	productId NUMBER,
    isMainImage VARCHAR(10),
	"path" VARCHAR2(200),
	"source" BLOB,
    
    CONSTRAINT PK_ProductImages PRIMARY KEY ("ID")
);

--------------------------------------------------------------------------------------------------------------------------------
-- NHÓM CÁC BẢNG HÓA ĐƠN

CREATE TABLE ThuongMaiDienTu_Web.Invoices
(
	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
	customerId NUMBER,
	orderDate TIMESTAMP NOT NULL,
	shipedDate TIMESTAMP,
	address1 NVARCHAR2(100), 
	address2 NVARCHAR2(100), 
	city NVARCHAR2(100),
	"state" NVARCHAR2(100),
	postalCode VARCHAR2(50),
	country NVARCHAR2(100),
	fee DECIMAL(19,4),
	paymentTypeId NUMBER NOT NULL,
	paidDate TIMESTAMP,
    invoiceStateId NUMBER NOT NULL, 
    totalMoney DECIMAL(19,4),
    
    CONSTRAINT PK_Invoices PRIMARY KEY ("ID")
);
 
CREATE TABLE ThuongMaiDienTu_Web.InvoiceStates
(
    "ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
	"name" NVARCHAR2(100) NOT NULL,
	"description" LONG,
	createAt TIMESTAMP,
	updateAt TIMESTAMP,
	
	CONSTRAINT PK_InvoiceStates PRIMARY KEY ("ID")
);

CREATE TABLE ThuongMaiDienTu_Web.InvoiceDetails
(
	invoiceId NUMBER,
	productId NUMBER,
	quanty INT NOT NULL,
	unitPrice DECIMAL(19,4) NOT NULL,
    intoMoney DECIMAL(19,4) NOT NULL,
    createAt TIMESTAMP,
	updateAt TIMESTAMP,
    
    CONSTRAINT PK_InvoiceDetails PRIMARY KEY (invoiceId, productId)
);

CREATE TABLE ThuongMaiDienTu_Web.PaymentTypes
(
	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
	"name" VARCHAR(50) NOT NULL,
	"description" LONG,
    createAt TIMESTAMP,
	updateAt TIMESTAMP,
    
    CONSTRAINT PK_PaymentTypes PRIMARY KEY ("ID")
);

--------------------------------------------------------------------------------------------------------------------------------
-- BẢNG LƯU SỰ KIỆN HỆ THỐNG

CREATE TABLE ThuongMaiDienTu_Web.StartupAudits 
(
  eventType  VARCHAR2(15),
  eventDate  DATE,
  eventTime  VARCHAR2(15)
);

--------------------------------------------------------------------------------------------------------------------------------
-- CÁC RÀNG BUỘC TOÀN VẸN

ALTER TABLE ThuongMaiDienTu_Web.Admins
ADD CONSTRAINT FK_Admins_Roles FOREIGN KEY (roleId) REFERENCES ThuongMaiDienTu_Web."Roles" ("ID")

ALTER TABLE ThuongMaiDienTu_Web.Products
ADD (
    CONSTRAINT FK_Products_ProductCategories FOREIGN KEY (productCategoryId) REFERENCES ThuongMaiDienTu_Web.ProductCategories ("ID"),
	CONSTRAINT FK_Products_Suppliers FOREIGN KEY (supplierId) REFERENCES ThuongMaiDienTu_Web.Suppliers ("ID"),
    CONSTRAINT FK_Product_ProductStates FOREIGN KEY (productStateId) REFERENCES ThuongMaiDienTu_Web.ProductStates ("ID"))

ALTER TABLE ThuongMaiDienTu_Web.ProductReviews
ADD (
    CONSTRAINT FK_ProductReviews_Products FOREIGN KEY (parentId) REFERENCES ThuongMaiDienTu_Web.Products ("ID"))
    
ALTER TABLE ThuongMaiDienTu_Web.ProductImages
ADD CONSTRAINT FK_ProductImages_Products FOREIGN KEY (productId) REFERENCES ThuongMaiDienTu_Web.Products ("ID")

ALTER TABLE ThuongMaiDienTu_Web.Invoices
ADD (
    CONSTRAINT FK_Invoices_Customers FOREIGN KEY (customerId) REFERENCES ThuongMaiDienTu_Web.Customers ("ID"),
    CONSTRAINT FK_Invoices_PaymentTypes FOREIGN KEY (paymentTypeId) REFERENCES ThuongMaiDienTu_Web.PaymentTypes ("ID"),
    CONSTRAINT FK_Invoice_InvoiceStates FOREIGN KEY (invoiceStateId) REFERENCES ThuongMaiDienTu_Web.InvoiceStates ("ID"))

ALTER TABLE ThuongMaiDienTu_Web.InvoiceDetails
ADD (
    CONSTRAINT FK_InvoiceDetails_Invoices FOREIGN KEY (invoiceId) REFERENCES ThuongMaiDienTu_Web.Invoices ("ID"),
    CONSTRAINT FK_InvoiceDetails_Products FOREIGN KEY (productId) REFERENCES ThuongMaiDienTu_Web.Products ("ID"))

-- BỔ SUNG CÁC RÀNG BUỘC TOÀN VẸN KHÁC: UNIQUE CONSTRAINT, CHECK CONSTRAINT, DEFAULT CONSTRAINT.
--- UNIQUE CONSTRAINT

Alter table ThuongMaiDienTu_Web.Customers 
Add constraint UNI_Customers unique(username);

Alter table ThuongMaiDienTu_Web.Admins
Add constraint UNI_Admins unique(usernames);

Alter table ThuongMaiDienTu_Web.ProductCategories
Add constraint UNI_ProductCategories unique("name");

Alter table ThuongMaiDienTu_Web.ProductStates
Add constraint UNI_ProductStates unique("name");

Alter table ThuongMaiDienTu_Web.InvoiceStates
Add constraint UNI_InvoiceStates unique("name");

--- CHECK CONSTRAINT

Alter table ThuongMaiDienTu_Web.Customers
Add constraint CHK_Customers check (gender = 'female' or gender = 'male');

Alter table ThuongMaiDienTu_Web.Admins
Add constraint CHK_Admins check (gender = 'female' or gender = 'male');

Alter table ThuongMaiDienTu_Web.Products
Add constraint CHK_Products check (quanty > 0);

Alter table ThuongMaiDienTu_Web.Invoices
Add constraint CHK_Invoices check (orderDate <= shipedDate);

--- DEFAULT CONSTRAINT

---------------------------------------------------------------------------------------------------------------------------------------------